### ISSUE TITLE
Drag

### ISSUE THREAD

**Issue by ydodone** [gildaswise/holding_gesture#1]
when child hold and dragged counter keeps increasing

**Comment by gildaswise** [comment]
Hey! This is an issue I don't really know how to solve because that's the default behaviour in every phone; if you press and hold something and then drag your finger, it'll still be targeting the button/inkwell you were pressing before. What exactly is your use-case and why is this a problem for you?

**Comment by ydodone** [comment]
But increment should stop when finger is up but cycles to end value even
after finger is up

**Comment by IhorKlimov** [comment]
@gildaswise 

Actually, drag happens unintentionally on devices. Basically, you can't just hold your finger on the same exact spot. Now and then it will slip from the touch area

**Comment by gildaswise** [comment]
@IhorKlimov Would a counter with max calls per holding solve the issue? I couldn't really figure it out if this is an issue with GestureDetector or not.

**Comment by IhorKlimov** [comment]
@gildaswise 

I'm working on a solution and got some promising stuff. Expect to see a PR this week probably

**Comment by gildaswise** [comment]
@IhorKlimov Thanks a lot, then! If that doesn't work, then I think just adding a limiter would be enough. e.g. "up to 50 calls are allowed per hold, then it cancels automatically"

**Comment by Pioxis** [comment]
Hello, I have problem with the same action. I'm using the newest version from pub.dev. When I double click, hold and drag finger from the button after that that button doesn't work, not recognize holding the button again. I have to reload app to renew working button.
