### ISSUE TITLE
HoldDetector and HoldTimeoutDetector Not Detecting with Specific Gesture

### ISSUE THREAD

**Issue by Awesomeplayer165** [gildaswise/holding_gesture#10]
When putting your finger on the HoldDetector or HoldTimeoutDetector and sliding your finger off before `onHold` is fired, then it would not fire `onHold` again.

**Comment by Awesomeplayer165** [comment]
It also calls `onTap` but still ignores `onHold`, and thus `onCancel`

**Comment by gildaswise** [comment]
This is intended behavior, if you need something to be done faster than the default timing then you can change the timeout duration; unless what you're saying is that the callback is not being called ever again after doing this, which I could not reproduce
