### ISSUE TITLE
No haptic feedback

### ISSUE THREAD

**Issue by ratsey** [gildaswise/holding_gesture#4]
Using the following code, I was expecting the device to 'vibrate' for haptic feedback. The action model.muteApp is called, but I don't sense anything on the device.

yaml set to holding_gesture: ^0.0.3

```
              Align(
                alignment: Alignment(0.9, 0.55),
                child: HoldDetector(
                  onHold: model.muteApp,
                  holdTimeout: Duration(milliseconds: 750),
                  enableHapticFeedback: true,
                  child: FloatingActionButton(
                    onPressed: () async {
                      await model.toggleSound();
                    },
                    child: model.getSoundButton(),                    
                    backgroundColor: Colors.white,
                  ),
                ),
              )
```

**Comment by gildaswise** [comment]
According to the [`HapticFeedback` docs](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/haptic_feedback.dart) seems like it won't work on an iOS device below version 10, are you using that? If it's on Android, it might be missing the VIBRATE permission somehow, try adding that to your `AndroidManifest.xml` and see if anything changes.
