### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by IchordeDionysos** [gildaswise/holding_gesture#5]
This is a request to add support for [null safety](https://dart.dev/null-safety) to `package:holding_gesture`.
We depend on your awesome package, so would be great to have null safety enabled.

The Dart/Flutter team already encourages publishing the migrated packages: See [this blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

See the [migration guide](https://dart.dev/null-safety/migration-guide) for details about enabling null safety.

**Comment by gildaswise** [comment]
Thanks for using it! It's up now! https://pub.dev/packages/holding_gesture/versions/1.0.0-dev

**Comment by IchordeDionysos** [comment]
@gildaswise wow thanks for your quick response 😍 Really appreciate it 💪
