### ISSUE TITLE
Feature request: detect when a hold has begun and ended

### ISSUE THREAD

**Issue by MagnusJohansson** [gildaswise/holding_gesture#7]
I was looking for a Gesture detector that enables me to do the following for a Button:
- When the user starts pressing the button, a progress bar is shown (either overlayed or somewhere else on the screen) with an event that resembles "onLongPressInitiated".
- If the user releases the button before the timeout/longPress event occurs , the Progress bar is hidden, onCancel fired
- If the user press and holds until the timeout has expired, the longPress event occurs. (And I can hide the progressbar)

I was hoping this library could do that, but I'm not being able to accomplish this.
I suppose it would be possible if it would expose an event that is something like "onLongPressInitiated".

Would this be possible?

**Comment by gildaswise** [comment]
Added `HoldTimeoutDetector` to solve this, and the example has been updated with your use-case.
