### ISSUE TITLE
Use with onTap

### ISSUE THREAD

**Issue by EliaTolin** [gildaswise/holding_gesture#9]
Hi,
I would like use your package with onTap, but it not works perfectly.
Sometimes the onTap with InkWell and LongPress with you package not works, is it possible a conflict? 
You see here:

https://github.com/EliaTolin/infinity_sweeper/blob/d52f39ccd5c5385dcf4fae5ac38e3314da640c16/lib/widgets/game/cell_widget.dart

You have suggest?

**Comment by gildaswise** [comment]
Have you tried using `HoldDetector` instead of `HoldTimeoutDetector`? It seems you're not really using the onTimerInitiated and onCancel methods which make the difference of the Timeout version
